FROM kalilinux/kali-last-release:latest

ENV DEBIAN_FRONTEND noninteractive

RUN set -e 							&& \
    apt-get update 						&& \
    apt-get upgrade -yq 					&& \
    apt-get install -yq --no-install-recommends			\
    	apt-utils						\
	build-essential						\
	ca-certificates						\
	curl							\
	elfutils						\
	gdb-multiarch						\
	gdbserver						\
	git							\
	glibc-source						\
	kali-linux-headless					\
	libc6-dev						\
	libc6-dbg						\
    	locales							\
	python3							\
	python3-dev						\
	python3-pip						\
	ripgrep							\
	strace							&& \
    python3 -m pip install --upgrade --no-cache-dir pip 	&& \
    usermod -s /bin/zsh root					&& \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' 	\
      /etc/locale.gen 						&& \
    dpkg-reconfigure --frontend=noninteractive locales 		&& \
    update-locale LANG=en_US.UTF-8 				&& \
    apt-get -y autoremove --purge 				&& \
    apt-get clean 						&& \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN set -e 							&& \
    git clone --depth 1 https://github.com/vobst/dotfiles	&& \
    yes | ./dotfiles/scripts/install.sh

WORKDIR /opt/gef
RUN set -e 							&& \
    curl -fsSL https://gef.blah.cat/py				\
        --output /opt/gef/gdbinit-gef.py			&& \
    echo "source /opt/gef/gdbinit-gef.py" >> ~/.gdbinit_local

RUN set -e 							&& \
    pip install							\
        pwntools						\
	keystone-engine						\
	ropper

WORKDIR /io
